# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sprockets-foo}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ben Curren}]
  s.date = %q{2011-10-28}
  s.description = %q{Enhancements for sprockets including templating support with ejs.}
  s.email = %q{ben@outright.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sprockets-foo.rb",
    "lib/sprockets/directives/template_directive.rb",
    "sprockets-foo.gemspec",
    "test/fixtures/requiring_a_file_that_does_not_exist_should_raise_an_error.js",
    "test/fixtures/requiring_a_template_should_compile_then_require.js",
    "test/fixtures/requiring_a_template_with_namespace_should_compile_then_require.js",
    "test/fixtures/src/MyTemplate.ejs",
    "test/fixtures/src/MyTemplate.js",
    "test/fixtures/src/or/ui/MyNamespacedTemplate.ejs",
    "test/fixtures/src/or/ui/MyNamespacedTemplate.js",
    "test/test_helper.rb",
    "test/test_template_directive.rb"
  ]
  s.homepage = %q{http://github.com/bcurren/sprockets-foo}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Enhancements for sprockets including templating support with ejs.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ejs-rcompiler>, [">= 0.1.3"])
    else
      s.add_dependency(%q<ejs-rcompiler>, [">= 0.1.3"])
    end
  else
    s.add_dependency(%q<ejs-rcompiler>, [">= 0.1.3"])
  end
end

