# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sprockets-foo}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Curren"]
  s.date = %q{2010-09-27}
  s.description = %q{Enhancements for sprockets including templating support with ejs.}
  s.email = %q{ben@outright.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/sprockets_with_directives/lib/sprockets.rb",
     "ext/sprockets_with_directives/lib/sprockets/concatenation.rb",
     "ext/sprockets_with_directives/lib/sprockets/directive.rb",
     "ext/sprockets_with_directives/lib/sprockets/directives.rb",
     "ext/sprockets_with_directives/lib/sprockets/directives/provide_directive.rb",
     "ext/sprockets_with_directives/lib/sprockets/directives/relative_require_directive.rb",
     "ext/sprockets_with_directives/lib/sprockets/directives/require_directive.rb",
     "ext/sprockets_with_directives/lib/sprockets/environment.rb",
     "ext/sprockets_with_directives/lib/sprockets/error.rb",
     "ext/sprockets_with_directives/lib/sprockets/pathname.rb",
     "ext/sprockets_with_directives/lib/sprockets/preprocessor.rb",
     "ext/sprockets_with_directives/lib/sprockets/secretary.rb",
     "ext/sprockets_with_directives/lib/sprockets/source_file.rb",
     "ext/sprockets_with_directives/lib/sprockets/version.rb",
     "ext/sprockets_with_directives/test/test_concatenation.rb",
     "ext/sprockets_with_directives/test/test_environment.rb",
     "ext/sprockets_with_directives/test/test_helper.rb",
     "ext/sprockets_with_directives/test/test_pathname.rb",
     "ext/sprockets_with_directives/test/test_preprocessor.rb",
     "ext/sprockets_with_directives/test/test_secretary.rb",
     "ext/sprockets_with_directives/test/test_source_file.rb",
     "ext/sprockets_with_directives/test/test_source_line.rb",
     "lib/sprockets-foo.rb",
     "lib/sprockets/directives/template_directive.rb",
     "sprockets-foo.gemspec",
     "test/fixtures/requiring_a_template_should_compile_then_require.js",
     "test/fixtures/requiring_a_template_with_namespace_should_compile_then_require.js",
     "test/fixtures/src/MyTemplate.ejs",
     "test/fixtures/src/MyTemplate.js",
     "test/fixtures/src/or/ui/MyNamespacedTemplate.ejs",
     "test/fixtures/src/or/ui/MyNamespacedTemplate.js",
     "test/test_helper.rb",
     "test/test_template_directive.rb"
  ]
  s.homepage = %q{http://github.com/bcurren/sprockets-foo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Enhancements for sprockets including templating support with ejs.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_template_directive.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ejs-rcompiler>, [">= 0.1.1"])
    else
      s.add_dependency(%q<ejs-rcompiler>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<ejs-rcompiler>, [">= 0.1.1"])
  end
end

