// Autogenerated from an Ejs file. Edits may be lost.


window.or = window.or || {};
window.or.ui = window.or.ui || {};
window.or.ui.MyNamespacedTemplate = window.or.ui.MyNamespacedTemplate || {};
or.ui.MyNamespacedTemplate.template = function(options) {
  var p = [];
  with(options) {
    p.push('<p>Content</p>\n');
  }
  return p.join('');
}