// Autogenerated from an Ejs file. Edits may be lost.


window.MyTemplate = window.MyTemplate || {};
MyTemplate.render = function(options) {
  var p = [];
  with(options) {
    p.push('<p>Content</p>\n');
  }
  return p.join('');
}